server:
  port: 8761
eureka:
  instance:
    hostname: peer1
eureka:
  client:
    registerWithEureka: false
eureka:
  client:
    fetchRegistry: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/

