server:
  port: 8762
eureka:
  instance:
    hostname: peer2
eureka:
  client:
    registerWithEureka: false
eureka:
  client:
    fetchRegistry: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/

